### ISSUE TITLE
Nala stops working

### ISSUE THREAD

**Issue by obtulowiczl** [volitank/nala#25]
Hello.
Today when I try update system, i get this error:

```
sudo nala upgrage
Traceback (most recent call last):
  File "/usr/local/bin/nala", line 5, in <module>
    from nala.__main__ import main
  File "/usr/local/lib/python3.10/dist-packages/nala/__main__.py", line 31, in <module>
    import nala.fetch as _fetch  # pylint: disable=unused-import
  File "/usr/local/lib/python3.10/dist-packages/nala/fetch.py", line 36, in <module>
    import typer
  File "/usr/lib/python3/dist-packages/typer/__init__.py", line 5, in <module>
    from click.exceptions import Abort as Abort
  File "/usr/lib/python3/dist-packages/click/__init__.py", line 7, in <module>
    from .core import Argument as Argument
ModuleNotFoundError: No module named 'click.core'

```

**Comment by SupianIDz** [comment]
pip3 install click

**Comment by volitank** [comment]
Which distro and release? I usually don't advise using pip to solve the issue. Packages should come from the distro whenever possible.

**Comment by afteroot** [comment]
Install nala 
`curl https://gitlab.com/volian/volian-archive/-/raw/main/install-nala.sh | bash`

```
$ cat /etc/os/release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)" 
NAME="Debian GNU/Linux" 
VERSION_ID="11" 
----
```
```
$ nala history                        
Traceback (most recent call last):
  File "/bin/nala", line 5, in <module>
    from nala.__main__ import main
  File "/usr/lib/python3/dist-packages/nala/__main__.py", line 31, in <module>
    import nala.fetch as _fetch  # pylint: disable=unused-import
  File "/usr/lib/python3/dist-packages/nala/fetch.py", line 36, in <module>
    import typer
  File "/usr/lib/python3/dist-packages/typer/__init__.py", line 30, in <module>
    from .main import Typer as Typer
  File "/usr/lib/python3/dist-packages/typer/main.py", line 16, in <module>
    from .completion import get_completion_inspect_parameters
  File "/usr/lib/python3/dist-packages/typer/completion.py", line 7, in <module>
    from ._completion_classes import completion_init
  File "/usr/lib/python3/dist-packages/typer/_completion_classes.py", line 8, in <module>
    import click.shell_completion
ModuleNotFoundError: No module named 'click.shell_completion'
```

**Comment by afteroot** [comment]
> Install nala `curl https://gitlab.com/volian/volian-archive/-/raw/main/install-nala.sh | bash`
> 
> ```
> $ cat /etc/os/release
> PRETTY_NAME="Debian GNU/Linux 11 (bullseye)" 
> NAME="Debian GNU/Linux" 
> VERSION_ID="11" 
> ----
> ```
> 
> ```
> $ nala history                        
> Traceback (most recent call last):
>   File "/bin/nala", line 5, in <module>
>     from nala.__main__ import main
>   File "/usr/lib/python3/dist-packages/nala/__main__.py", line 31, in <module>
>     import nala.fetch as _fetch  # pylint: disable=unused-import
>   File "/usr/lib/python3/dist-packages/nala/fetch.py", line 36, in <module>
>     import typer
>   File "/usr/lib/python3/dist-packages/typer/__init__.py", line 30, in <module>
>     from .main import Typer as Typer
>   File "/usr/lib/python3/dist-packages/typer/main.py", line 16, in <module>
>     from .completion import get_completion_inspect_parameters
>   File "/usr/lib/python3/dist-packages/typer/completion.py", line 7, in <module>
>     from ._completion_classes import completion_init
>   File "/usr/lib/python3/dist-packages/typer/_completion_classes.py", line 8, in <module>
>     import click.shell_completion
> ModuleNotFoundError: No module named 'click.shell_completion'
> ```
```
$ pip list | grep click   
click                         7.1.2
click-option-group            0.5.6
```

**Comment by afteroot** [comment]
> apt upgrade -t nala

Thanks for update!
Confirmed, works like a charm

```bash
$ sudo apt upgrade -t nala
Зчитування переліків пакунків... Виконано
Побудова дерева залежностей... Виконано            
Зчитування інформації про стан... Виконано   
Обчислення оновлень... Виконано
Наступні пакунки були встановлені автоматично і більше не потрібні:
  python3-commonmark python3-rfc3986
Використовуйте 'sudo apt autoremove' щоб видалити їх.
НОВІ пакунки, які будуть встановлені:
  python3-exceptiongroup python3-markdown-it python3-mdurl
Пакунки, які залишені в незмінному стані:
  python3-pkg-resources
Пакунки, які будуть ОНОВЛЕНІ:
  python3-anyio python3-click python3-commonmark python3-h11 python3-httpcore python3-httpx python3-rich python3-typing-extensions
оновлено 8, встановлено 3 нових, 0 відмічено для видалення і 1 не оновлено.
Необхідно завантажити 725 kB архівів.
Після цієї операції об'єм зайнятого дискового простору зросте на 1 237 kB.
Бажаєте продовжити? [Y/n] 
Отр:1 https://deb.volian.org/volian nala/main amd64 python3-exceptiongroup all 1.2.0-1 [19,3 kB]
Отр:2 https://deb.volian.org/volian nala/main amd64 python3-typing-extensions all 4.10.0-1 [66,2 kB]
Отр:3 https://deb.volian.org/volian nala/main amd64 python3-anyio all 4.3.0-1 [56,5 kB]
Отр:4 https://deb.volian.org/volian nala/main amd64 python3-click all 8.1.7-1 [94,0 kB]
Отр:5 https://deb.volian.org/volian nala/main amd64 python3-commonmark all 0.9.1-5 [45,1 kB]
Отр:6 https://deb.volian.org/volian nala/main amd64 python3-h11 all 0.14.0-1 [50,1 kB]
Отр:7 https://deb.volian.org/volian nala/main amd64 python3-httpcore all 1.0.4-1 [44,5 kB]
Отр:8 https://deb.volian.org/volian nala/main amd64 python3-mdurl all 0.1.2-1 [9 444 B]
Отр:9 https://deb.volian.org/volian nala/main amd64 python3-markdown-it all 3.0.0-2 [62,5 kB]
Отр:10 https://deb.volian.org/volian nala/main amd64 python3-rich all 13.7.1-1 [201 kB]
Отр:11 https://deb.volian.org/volian nala/main amd64 python3-httpx all 0.27.0-1 [76,8 kB]
----
```
```bash
$sudo nala fetch
Fetching Debian mirrors…
╭─  Selected Mirrors ────────────────────────────────────────────────────╮
│                                                                        │
│   Index    Mirror                                   Score              │
│       1    https://debian.volia.net/debian/         17 ms              │
│       2    https://mirror.mirohost.net/debian/      20 ms              │
│       3    https://ftp.bme.hu/debian/               22 ms              │
│       4    http://mirror.cloudhosting.lv/debian/    24 ms              │
│       5    http://debian.superhosting.cz/debian/    26 ms              │
│       6    http://ftp.debian.sk/debian/             26 ms              │
│       7    http://debian.carnet.hr/debian/          27 ms              │
│       8    http://ftp.antik.sk/debian/              27 ms              │
│       9    http://ftp.hr.debian.org/debian/         27 ms              │
│      10    http://ftp.it.debian.org/debian/         27 ms              │
│      11    http://ftp.sk.debian.org/debian/         27 ms              │
│      12    http://ftp.si.debian.org/debian/         28 ms              │
│      13    http://debian.ipacct.com/debian/         29 ms              │
│      14    http://debian.sil.at/debian/             29 ms              │
│      15    http://ftp.nl.debian.org/debian/         29 ms              │
│      16    http://ftp.pl.debian.org/debian/         29 ms              │
│                                                                        │
│   Score is how many milliseconds it takes to download the Release file │
╰────────────────────────────────────────────────────────────────────────╯
Are these mirrors okay? [Y/n]                                                                                                                                                                 
Sources have been written to /etc/apt/sources.list.d/nala-sources.list
```

**Comment by volitank** [comment]
This GitHub repository is a mirror and issues are not tracked here.

If this is still an issue, please report it on the canonical GitLab repository:
https://gitlab.com/volian/nala/-/issues

Thanks!
