### ISSUE TITLE
unable to use nala

### ISSUE THREAD

**Issue by AnirudhG07** [volitank/nala#52]
I installed nala with `sudo apt install nala` in my Ubuntu.
Here is what happens when i run it - 

```bash
❯ nala --version
Traceback (most recent call last):
  File "/usr/bin/nala", line 5, in <module>
    from nala.__main__ import main
  File "/usr/lib/python3/dist-packages/nala/__main__.py", line 30, in <module>
    import nala.fetch as _fetch  # pylint: disable=unused-import
  File "/usr/lib/python3/dist-packages/nala/fetch.py", line 37, in <module>
    import typer
  File "/usr/lib/python3/dist-packages/typer/__init__.py", line 12, in <module>
    from click.termui import get_terminal_size as get_terminal_size
ImportError: cannot import name 'get_terminal_size' from 'click.termui' (/home/anirudhgupta/.local/lib/python3.10/site-packages/click/termui.py)
```

I am unable to do anything with it. Please help!

**Comment by AnirudhG07** [comment]
Solution [here](https://gitlab.com/volian/nala/-/issues/331#note_2166785434). Thank you!
